name: Tokenizer CI

on:
  push:
    paths:
      - 'tokenizer/**'
  pull_request:
    paths:
      - 'tokenizer/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('tokenizer/**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Test Tokenizer Module
        run: mvn test
        working-directory: ./tokenizer